### ISSUE TITLE
Provide an endpoint returning the last time a given test has been executed

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-gtk-vnv#30]
[user story #342](https://git.cs.upb.de/5gtango/UserStories/issues/342)

**Comment by jbonnet** [comment]
@felipevicens, @luishens01 (cc @anapolg)
We need to design, implement, test and document this.

My proposal is something very similar to #29 (number of times the test has been executed). What do you think? Is this the simplest possible implementation of it?

From the outside, I suggest the following API: `GET .../api/v3/tests/descriptors/:test_uuid/last-executed-at`. Would this be ok, @anapolg ?

**Comment by jbonnet** [comment]
Even better, @anapolg: I'll include it in the enriched test descriptor (`GET .../api/v3/tests/descriptors/:test_uuid`), just like the number of executions, ok?

**Comment by anapolg** [comment]
@jbonnet yes, better in .../api/v3/tests/descriptors/:test_uui as another field of the test detailed information.
